services:
      - type: web
          name: dfindexer
              env: docker
                  plan: free
                      autoDeploy: false
                          dockerfilePath: ./Dockerfile
                              envVars:
                                    - key: PUID
                                            value: 1000
                                                  - key: PGID
                                                          value: 1000
                                                                - key: TZ
                                                                        value: America/Recife
                                                                            ports:
                                                                                  - port: 7006
